name: darkslip
description: A dark-mode note-taking app with folder hierarchy and chat-like markdown posts.
publish_to: 'none' # Remove if you plan to publish to pub.dev

version: 2026.06.08+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2
  flutter_markdown: ^0.7.3
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  path: ^1.9.1
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path_android: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21